### ISSUE TITLE
Issue with files data in the SSA archive

### ISSUE THREAD

**Issue by GioMetal** [EE-modders/SSA-tool#2]
Every file seems to start with PK01, and writing the data starting from the specified absolute position in the file entry is useless
![image](https://user-images.githubusercontent.com/43532487/187767060-a7ad09ce-a6dd-438e-8610-2124a38c4a73.png)

**Comment by zocker-160** [comment]
Yes because the data is DCL compressed. 

SSA tool includes a DCL decompressor for that reason, just make sure you select the decompression option when being asked.

**Comment by GioMetal** [comment]
@zocker-160 I was reading the documentation, i didn't see anything about compression, and since i'm noob in this field, i made this post to ask for help. soon later i found the source code and saw that you ckeck for magic to see if a file is compressed or not,
so at this point is clear why PK01 is there and what i should do. Thank you for your amazing work.

**Comment by zocker-160** [comment]
@GioMetal yes the documentation is lacking this information, sorry about that. 

I do actually have an updated version of it, which I haven't pushed to this repo for whatever reason. ._.
